version: "3.4"

services:
  postgres:
    image: postgres
    container_name: iha_postgres
    restart: always
    volumes:
      - iha-postgres-data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=250'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iha
      TZ: Europe/Istanbul
    ports:
      - "5432:5432"
    networks:
      - iha-network

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - iha-network


volumes:
  iha-postgres-data:
    driver: local

networks:
  iha-network:
    name: iha-network
    driver: bridge
