# Generated by Django 5.1.4 on 2025-01-06 06:46

from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from parts.models import PartType


def create_part_type_data(apps, schema_editor):
    # Parça Tipleri
    part_types = [
        {"name": "Kanat"},
        {"name": "Gövde"},
        {"name": "Kuyruk"},
        {"name": "Aviyonik"},
    ]

    PartType = apps.get_model("parts", "PartType")
    for type_data in part_types:
        part_type, created = PartType.objects.get_or_create(**type_data)
        if created:  # Sadece yeni oluşturulan PartType için izin ekleyelim
            content_type = ContentType.objects.get_for_model(PartType)
            Permission.objects.get_or_create(
                codename=f"produce_{part_type.name.lower()}",
                name=f"Can produce {part_type.name}",
                content_type=content_type,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_part_type_data),
    ]
