# Generated by Django 5.1.4 on 2025-01-06 06:39

from django.db import migrations


def create_aircraft_model_data(apps, schema_editor):
    # Uçak Modelleri
    aircraft_models = [
        {"name": "TB2"},
        {"name": "TB3"},
        {"name": "AKINCI"},
        {"name": "KIZILELMA"},
    ]
    AircraftModel = apps.get_model("aircrafts", "AircraftModel")
    for model_data in aircraft_models:
        AircraftModel.objects.get_or_create(**model_data)


class Migration(migrations.Migration):

    dependencies = [
        ("aircrafts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_aircraft_model_data),
    ]
